author:
  name: Stu Coston
  email: stu.coston@gmail.com
title: life captured
name: SC Media
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6684588
  brandStrength: 0.8297491
  lightness: 0.469534
  brandColors:
    - '#000000'
    - '#C0BCB1'
    - '#85887F'
    - '#444847'
    - '#E2E1DC'
  rhythmicContrast: 0
typography_spectrum: 0.5752688
layout_spectrum: 0.5806451
analytics:
  twitter: '@stucoston'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a581ab95-f871-4e11-abf7-8a205aacd0f3.tiff
