typography_spectrum: 0.5752688
color:
  saturation: 0.6003584
  brandStrength: 1
  lightness: 0.3763441
  brandColors:
    - '#262626'
    - '#7F7F7F'
    - '#0C0C0C'
    - '#555555'
    - '#873710'
  rhythmicContrast: 0
layout_spectrum: 0.5806451
analytics:
  twitter: '@stucoston'
author:
  name: Stu Coston
  email: stu.coston@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/75f34a98-8823-4f1e-9e29-12e60f73654b.jpg
name: Stu Coston Media
navigation:
  - url: www.costonmission.com
    name: Coston Mission
    type: external
  - id: 8b758305-5506-443f-985b-253e9d56ee4a
    name: Videos
    type: content
  - id: f2fe7f42-2b0b-4bed-8312-ebda7661ee97
    name: Connect
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d2f95625-fd78-4a5b-a75c-7a8a7e997d5d.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ''
